name: Main

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                node-version: [16]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                os: [macos-latest, ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
            - run: npm run dev:setup
            - run: npm ci
            - run: npm run build
            - name: Mocha Tests with coverage
              run: npm run uuid4:lcov
            - name: Coveralls GitHub Action
              if: matrix.os == 'ubuntu-20.04' && matrix.node-version == '16.x'
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.github_token }}
